image: Visual Studio 2017

# Don't run the (redundant) branch build with a pull request
skip_branch_with_pr: true

environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\tools\\appveyor\\run_with_env.cmd"
  COVERALLS_REPO_TOKEN:
    secure: ZaE7K9EHorv40AjYhSuWtQeRAsMN1+QqPf7u8rOlvEY50kdaHj87Mh5GIDZgJBzj
  CONDA_INSTRUMENTATION_ENABLED: "true"
  matrix:
    # Note that we're using Python 3 for package builds even when building
    # the Python 2.7 version of the package. This is because of an issue
    # unpacking the menuinst .conda package on p27
    - PYTHON_VERSION: "3.6"
      TEST_MODE: "not integration"
      CONDA_ROOT: "C:\\Miniconda36-x64"
    - PYTHON_VERSION: "2.7"
      TEST_MODE: "not integration"
      CONDA_ROOT: "C:\\Miniconda"
    - PYTHON_VERSION: "3.6"
      TEST_MODE: "integration"
      CONDA_ROOT: "C:\\Miniconda36-x64"
    - PYTHON_VERSION: "2.7"
      TEST_MODE: "integration"
      CONDA_ROOT: "C:\\Miniconda"
    - PYTHON_VERSION: "3.6"
      TEST_MODE: "package"
      CONDA_ROOT: "C:\\Miniconda36-x64"
    - PYTHON_VERSION: "2.7"
      TEST_MODE: "package"
      CONDA_ROOT: "C:\\Miniconda36"

#init:
  # - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

# conda install -y -c defaults -c conda-forge pytest pytest-cov pytest-timeout mock responses pexpect xonsh
# TODO: add xonsh for PY3 builds  
install:
  - call %CONDA_ROOT%\Scripts\activate.bat
  - if "%TEST_MODE%" == "package" (
      conda install -yq conda conda-build=3.17
    ) else (
      conda install -yq python=%PYTHON_VERSION% conda conda-build=3.17 &&
      conda install -yq pycosat requests ruamel_yaml pytest pytest-cov pytest-timeout mock responses urllib3 pexpect pywin32 anaconda-client conda-package-handling &&
      pip install codecov==2.0.5 &&
      conda init cmd.exe --dev
    )

build: false

# There has to be a better way to do this, but AppVeyor is finicky with multi-line scripts
test_script:
  - call %CONDA_ROOT%\Scripts\activate.bat
  - if "%PYTHON_VERSION" == "2.7" (set PYTHON_ARCH="32") else (set PYTHON_ARCH="64")
  - if "%TEST_MODE%" == "package" (
      conda-build conda.recipe --python=%PYTHON_VERSION%
    ) else (
      call dev-init.bat &&
      (if "%TEST_MODE%" == "integration" conda-build tests\test-recipes\activate_deactivate_package) &&
      py.test -m "%TEST_MODE% and not installed" -v --basetemp=C:\tmp &&
      curl -s https://codecov.io/bash > codecov_uploader.sh &&
      bash -c ". codecov_uploader.sh -f coverage.xml" &&
      python -m conda.common.io
    )
